version: '3.8'

services:
  task-manager:
    build: .
    container_name: task-manager
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
