"""init

Revision ID: 2cc1e256d10b
Revises: 
Create Date: 2025-09-18 23:30:40.963302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cc1e256d10b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.CheckConstraint('importance BETWEEN 1 AND 5', name='importance_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_completed', 'tasks', ['completed'], unique=False)
    op.create_index('ix_task_due_date', 'tasks', ['due_date'], unique=False)
    op.create_index('ix_task_importance', 'tasks', ['importance'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index('ix_task_importance', table_name='tasks')
    op.drop_index('ix_task_due_date', table_name='tasks')
    op.drop_index('ix_task_completed', table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
